
warning_threshold: 15

excluded: 
  - Last.fm client/Support Files/AppDelegate.swift
  - Pods

file_length:
  warning: 500
  error: 600

cyclomatic_complexity:
  warning: 20
  error: 30

type_body_length:
  warning: 300
  error: 400